version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    volumes:
      - mydata:/var/lib/mysql
    networks:
      - backend

  spring-app:
    build: .
    container_name: student-app
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend

networks:
  backend:

volumes:
  mydata: